/* Dữ liệu điểm đến – dùng chung cho thẻ, bản đồ, modal */
var DESTS = [
  {
    id: 1,
    name: 'VQG Yok Đôn',
    cat: 'rung',
    catL: 'Rừng & Động vật',
    emo: '🦁',
    img: ['../assets/yokdon1.jpg', '../assets/yokdon2.jpg', '../assets/yokdon3.jpg'],
    gal: ['🦁', '🌳', '🦜'],
    rating: 4.9,
    rev: 640,
    loc: 'Huyện Buôn Đôn',
    lat: 13.1,
    lng: 107.75,
    price: 'Từ 200.000đ',
    bestTime: 'Tháng 11 – 5',
    dur: '2–3 ngày',
    desc: 'Khu bảo tồn thiên nhiên rộng nhất Việt Nam – voi châu Á, bò tót, hổ…',
    long: 'VQG Yok Đôn có 115.545 ha rừng khộp, hơn 464 loài thực vật và 89 loài thú.',
    hl: ['Trekking rừng nguyên sinh', 'Cắm trại qua đêm', 'Ngắm động vật hoang dã', 'Kayak sông Sêrêpốk'],
    tags: ['rung']
  },
  {
    id: 2,
    name: 'Hồ Lắk',
    cat: 'ho',
    catL: 'Hồ & Thiên nhiên',
    emo: '🏞️',
    img: ['../assets/holak1.jpg', '../assets/holak2.jpg', '../assets/holak3.jpg'],
    gal: ['🏞️', '🚣', '🌅'],
    rating: 4.7,
    rev: 980,
    loc: 'Huyện Lắk',
    lat: 12.3831,
    lng: 108.1765,
    price: 'Từ 50.000đ',
    bestTime: 'Tháng 12 – 4',
    dur: '1 ngày',
    desc: 'Hồ tự nhiên lớn nhất Tây Nguyên với diện tích 500 ha.',
    long: 'Hồ Lắk rộng khoảng 500 ha, sâu trung bình 4–5 m. Du khách có thể đi thuyền độc mộc, thăm Biệt điện Bảo Đại.',
    hl: ['Chèo thuyền độc mộc', 'Ngắm bình minh trên hồ', 'Thăm Biệt điện Bảo Đại', "Làng dân tộc M'nông"],
    tags: ['ho', 'vanHoa']
  },
  {
    id: 3,
    name: 'TP. Buôn Ma Thuột',
    cat: 'thanhPho',
    catL: 'Thành phố',
    emo: '☕',
    img: ['../assets/bmt1.jpg', '../assets/bmt2.jpg', '../assets/bmt3.jpg'],
    gal: ['☕', '🏙️', '🎋'],
    rating: 4.5,
    rev: 2100,
    loc: 'TP. Buôn Ma Thuột',
    lat: 12.6667,
    lng: 108.05,
    price: 'Từ 0đ',
    bestTime: 'Quanh năm',
    dur: '2–3 ngày',
    desc: 'Thủ phủ cà phê Việt Nam – Bảo tàng Thế giới Cà phê độc đáo.',
    long: 'Buôn Ma Thuột là trung tâm kinh tế văn hóa Đắk Lắk, được mệnh danh thủ phủ cà phê Việt Nam.',
    hl: ['Bảo tàng Thế giới Cà phê', 'Thưởng thức cà phê rang xay', 'Bảo tàng Đắk Lắk', 'Chợ đêm Buôn Ma Thuột'],
    tags: ['thanhPho', 'vanHoa']
  },
  {
    id: 4,
    name: 'Thác Dray Nur',
    cat: 'thac',
    catL: 'Thác nước',
    emo: '💧',
    img: ['../assets/draynur1.jpg', '../assets/draynur2.jpg', '../assets/draynur3.jpg'],
    gal: ['💧', '🌊', '🌿'],
    rating: 4.6,
    rev: 750,
    loc: 'Huyện Krông Ana',
    lat: 12.492,
    lng: 108.089,
    price: 'Từ 30.000đ',
    bestTime: 'Tháng 5 – 11',
    dur: 'Nửa ngày',
    desc: "Thác nước hùng vĩ trên sông Sêrêpốk – 'Dray Nur' nghĩa là thác vợ.",
    long: 'Thác Dray Nur cùng Dray Sap tạo cặp thác đôi huyền thoại trên sông Sêrêpốk, rộng hơn 150m.',
    hl: ['Ngắm thác nước hùng vĩ', 'Chụp ảnh sương mù thác', 'Khám phá rừng ven thác', 'Cặp thác Dray Sap – Dray Nur'],
    tags: ['thac', 'rung']
  },
];
