/* Dữ liệu điểm đến – dùng chung cho thẻ, bản đồ, modal */
var DESTS = [
  {
    id: 1,
    name: 'Vườn QG Buôn Đôn',
    cat: 'rung',
    catL: 'Rừng & Động vật',
    emo: '🐘',
    gal: ['🐘', '🌿', '🦅'],
    rating: 4.8,
    rev: 1240,
    loc: 'Huyện Buôn Đôn',
    lat: 13.0294,
    lng: 107.8571,
    price: 'Từ 150.000đ',
    bestTime: 'Tháng 11 – 4',
    dur: '1–2 ngày',
    desc: 'Vườn quốc gia nổi tiếng với văn hóa thuần hóa voi của người Mnông và cảnh quan rừng nguyên sinh hùng vĩ.',
    long: 'Buôn Đôn gắn liền với nghề thuần dưỡng voi của người Mnông. VQG Yok Đôn rộng hơn 115.000 ha là khu bảo tồn thiên nhiên lớn nhất Việt Nam.',
    hl: ['Cưỡi voi qua rừng nguyên sinh', 'Thăm làng dân tộc Mnông', 'Xem biểu diễn cồng chiêng', 'Tắm voi tại sông Sêrêpốk'],
    tags: ['rung', 'vanHoa']
  },
  {
    id: 2,
    name: 'Hồ Lắk',
    cat: 'ho',
    catL: 'Hồ & Thiên nhiên',
    emo: '🏞️',
    gal: ['🏞️', '🚣', '🌅'],
    rating: 4.7,
    rev: 980,
    loc: 'Huyện Lắk',
    lat: 12.3831,
    lng: 108.1765,
    price: 'Từ 50.000đ',
    bestTime: 'Tháng 12 – 4',
    dur: '1 ngày',
    desc: 'Hồ tự nhiên lớn nhất Tây Nguyên với diện tích 500 ha.',
    long: 'Hồ Lắk rộng khoảng 500 ha, sâu trung bình 4–5 m. Du khách có thể đi thuyền độc mộc, thăm Biệt điện Bảo Đại.',
    hl: ['Chèo thuyền độc mộc', 'Ngắm bình minh trên hồ', 'Thăm Biệt điện Bảo Đại', "Làng dân tộc M'nông"],
    tags: ['ho', 'vanHoa']
  },
  {
    id: 3,
    name: 'TP. Buôn Ma Thuột',
    cat: 'thanhPho',
    catL: 'Thành phố',
    emo: '☕',
    gal: ['☕', '🏙️', '🎋'],
    rating: 4.5,
    rev: 2100,
    loc: 'TP. Buôn Ma Thuột',
    lat: 12.6667,
    lng: 108.05,
    price: 'Từ 0đ',
    bestTime: 'Quanh năm',
    dur: '2–3 ngày',
    desc: 'Thủ phủ cà phê Việt Nam – Bảo tàng Thế giới Cà phê độc đáo.',
    long: 'Buôn Ma Thuột là trung tâm kinh tế văn hóa Đắk Lắk, được mệnh danh thủ phủ cà phê Việt Nam.',
    hl: ['Bảo tàng Thế giới Cà phê', 'Thưởng thức cà phê rang xay', 'Bảo tàng Đắk Lắk', 'Chợ đêm Buôn Ma Thuột'],
    tags: ['thanhPho', 'vanHoa']
  },
  {
    id: 4,
    name: 'Thác Dray Nur',
    cat: 'thac',
    catL: 'Thác nước',
    emo: '💧',
    gal: ['💧', '🌊', '🌿'],
    rating: 4.6,
    rev: 750,
    loc: 'Huyện Krông Ana',
    lat: 12.492,
    lng: 108.089,
    price: 'Từ 30.000đ',
    bestTime: 'Tháng 5 – 11',
    dur: 'Nửa ngày',
    desc: "Thác nước hùng vĩ trên sông Sêrêpốk – 'Dray Nur' nghĩa là thác vợ.",
    long: 'Thác Dray Nur cùng Dray Sap tạo cặp thác đôi huyền thoại trên sông Sêrêpốk, rộng hơn 150m.',
    hl: ['Ngắm thác nước hùng vĩ', 'Chụp ảnh sương mù thác', 'Khám phá rừng ven thác', 'Cặp thác Dray Sap – Dray Nur'],
    tags: ['thac', 'rung']
  },
  {
    id: 5,
    name: 'VQG Yok Đôn',
    cat: 'rung',
    catL: 'Rừng & Động vật',
    emo: '🦁',
    gal: ['🦁', '🌳', '🦜'],
    rating: 4.9,
    rev: 640,
    loc: 'Huyện Buôn Đôn',
    lat: 13.1,
    lng: 107.75,
    price: 'Từ 200.000đ',
    bestTime: 'Tháng 11 – 5',
    dur: '2–3 ngày',
    desc: 'Khu bảo tồn thiên nhiên rộng nhất Việt Nam – voi châu Á, bò tót, hổ…',
    long: 'VQG Yok Đôn có 115.545 ha rừng khộp, hơn 464 loài thực vật và 89 loài thú.',
    hl: ['Trekking rừng nguyên sinh', 'Cắm trại qua đêm', 'Ngắm động vật hoang dã', 'Kayak sông Sêrêpốk'],
    tags: ['rung']
  },
  {
    id: 6,
    name: 'Khu ST Cỏ Thơm',
    cat: 'sinhThai',
    catL: 'Sinh thái',
    emo: '🌾',
    gal: ['🌾', '🌻', '🦋'],
    rating: 4.4,
    rev: 480,
    loc: 'Huyện Cư Kuin',
    lat: 12.52,
    lng: 108.15,
    price: 'Từ 80.000đ',
    bestTime: 'Tháng 11 – 4',
    dur: '1 ngày',
    desc: 'Khu du lịch sinh thái nông nghiệp – đồi cỏ, vườn hoa, thu hoạch cà phê.',
    long: 'Khu Cỏ Thơm cho trải nghiệm hái cà phê, học rang và vườn hoa hướng dương.',
    hl: ['Hái cà phê theo mùa', 'Chụp ảnh vườn hoa', 'Học rang cà phê', 'Ẩm thực dân tộc'],
    tags: ['sinhThai', 'rung']
  }
];
